# ------------------------------------------
# CUSTOMIZABLE TEMPLATE REPOSITORY VARIABLES
# 
environment:
  APP_DIR_NAME: "NET Assembly Info ShellEx"
  SOLUTION_EXT: "sln"
# ------------------------------------------

version: CI Build {Build}
skip_commits:
  files:
  - '.github/**/*'
  - 'Docs/**/*'
  - 'Documents/**/*'
  - 'Manual/**/*'
  - 'Images/**/*'
  - 'Scripts/**/*'
  - 'Website/**/*'
  - '*.md'
  - '*.zip'
  - '*.yml'
image: Visual Studio 2026
configuration: Release
install:
  - ps: Invoke-WebRequest -Uri "https://download.visualstudio.microsoft.com/download/pr/6f083c7e-bd40-44d4-9e3f-ffba71ec8b09/9ba926620d8e7568cbd0b84c7177a984/ndp481-devpack-enu.exe" -OutFile "$env:TEMP\ndp481-devpack.exe"
  - cmd: "%TEMP%\ndp481-devpack.exe" /q /norestart
  - cmd: git submodule update --init --recursive
  - >-
    git submodule update --init --recursive
before_build:
  - >-
    nuget restore "Source\%APP_DIR_NAME%.%SOLUTION_EXT%"
  - >-
    dotnet nuget locals all --clear
build:
  project: Source\%APP_DIR_NAME%.%SOLUTION_EXT%
  parallel: true
after_build:
  - >-
    7z a -r "%APPVEYOR_PROJECT_NAME%_Build_%APPVEYOR_BUILD_NUMBER%.zip" ^
    ".\Source\%APP_DIR_NAME%\bin\*" 
artifacts:
  - path: "%APPVEYOR_PROJECT_NAME%_Build_%APPVEYOR_BUILD_NUMBER%.zip"
    name: "%APPVEYOR_PROJECT_NAME%"